services:
  db:
    container_name: dressed-db
    image: postgres:18
    hostname: ${PGHOST}
    restart: always
    environment:
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    ports:
      - "5432:${PGPORT}"
    volumes:
      - pgdata:/var/lib/postgresql/MAJOR/docker
      - ./init-test-db.sql:/docker-entrypoint-initdb.d/init-test-db.sql
      - .:/app

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  pgdata:
